project:
  type: website
  output-dir: docs

website:
  title: "Mark Velthoen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Education
      - href: project_page.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
  

format:
  html:
    mainfont: Nunito
    theme: cosmo
    css: styles.scss
    toc: true
    page-layout: full

editor: visual

