project:
  type: website
  output-dir: docs

website:
  title: "Mark Velthoen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Education
      - href: project_page.qmd
        text: Projects
      - href: Mark Velthoen's Resume (13).pdf
        text: Resume
        target: _blank
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

