---
title: "Resume"
format: html
---

Mark Velthoen
6774 Trigo Rd Goleta, CA 93117
markvelthoen1@gmail.com
(805) 836-1150

EDUCATION
University of California, Santa Barbara
Bachelor of Science, Hydrologic Sciences and Policy - BS (Expected Graduation: June 2027), GPA: 3.77

PROFESSIONAL EXPERIENCE
Lifeguard
YMCA – Summer 2024 (20 hours/week)
Supervised pool areas and aquatic facilities to ensure the safety and well-being of all patrons.
Prepared to respond to emergencies with quick and effective first aid and CPR.
Enforced pool safety rules and provided assistance to visitors.
Collaborated with team members to ensure smooth daily operations and customer satisfaction.
Research Assistant
KSE Global - Full-time · July 2025- August 2025
Served as an assistant providing instruction, guidance and support within the AI and Machine Learning for Environmental Solutions track. 
Acted as a residential counselor, ensuring student safety, engagement and fostering a supportive environment in an academic setting.

VOLUNTEER EXPERIENCE
Sprout Up Volunteer
University of California, Santa Barbara – April 2025-Present
Delivered weekly environmental science lessons to elementary school students, fostering ecological awareness and sustainable habits in youth.
Developed and implemented interactive activities to engage students in topics such as recycling, water conservation, and biodiversity.
Collaborated with a team of volunteers to tailor curriculum content to different age groups and classroom needs.
Isla Vista Community Ambassador
University of California, Santa Barbara – September 2024–January 2025 (10 hours/quarter)
Serve as a liaison between UCSB students and the local Isla Vista community, fostering positive relationships.
Organize and participate in community outreach events focused on sustainability, social issues, and local engagement.
Contribute to initiatives that improve the quality of life and promote social responsibility within the community.

LEADERSHIP & EXTRACURRICULAR ACTIVITIES
Hydrology Club Member
University of California, Santa Barbara – September 2024–Present
Collaborated with a team of students to develop and promote environmental sustainability initiatives on campus.
Participated in events and workshops to raise awareness about water issues.
Recreational Tennis Club Member
University of California, Santa Barbara – September 2023–Present
Participate in weekly practice sessions and recreational matches to improve tennis skills.
Contribute to team events and foster a positive and inclusive environment within the club.

SKILLS & CERTIFICATIONS
First Aid & CPR Certified
Strong communication and interpersonal skills
Proficient in Microsoft Office Suite (Word, Excel, PowerPoint)
